# Generated by Django 4.1.3 on 2022-11-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unidade_consumidora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estacao_bobeamento", models.CharField(max_length=60)),
                ("demanda_contratada", models.FloatField()),
                ("conta_contrato", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Demanda_complementar_kw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.FloatField()),
                ("preco", models.FloatField()),
                ("valor", models.FloatField()),
                (
                    "estacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.unidade_consumidora",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Demanda_ativa_kw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.FloatField()),
                ("preco", models.FloatField()),
                ("valor", models.FloatField()),
                (
                    "estacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.unidade_consumidora",
                    ),
                ),
            ],
        ),
    ]
